name: Rust

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Update submodules
      run: git submodule update --init
    - name: Build contract
      run: make all-via-docker
    - name: Run omni_lock tests
      run: cd tests/omni_lock_rust && cargo test
#    - name: Run omni_lock simulator tests
#      run: cd tests/omni_lock && bash run.sh
